### ISSUE TITLE
hoog: personen toevoegen aan team 

### ISSUE THREAD

**Issue by marcplaggenburg** [brtwrs/GCS-issues#18]
SVP ipv email adres personen toevoegen obv CREW overzicht personen toevoegen aan een team. 
Sommige mensen hebben onbegonnen email adressen, zoeken op naam is wellicht handiger om snel een team samen te stellen.

**Comment by brtwrs** [comment]
Je hebt nu een dropdown met alle namen+emails. Ik kan hier nog een filter op bouwen maar dat kost wat extra tijd. Ik denk dat dit voor nu voldoende is? Zoniet dan reopen dit issue maar
