### ISSUE TITLE
in 1 keer meerdere dezelfde hardware toevoegen aan location

### ISSUE THREAD

**Issue by ynicoletti** [brtwrs/GCS-issues#22]
Wat fijn zou zijn is dat als een locatie als voorbeeld 6 ap's heeft dat we bij het toevoegen van hardwarde het aantal kunnen kiezen of bij het al toegevoegde hardware een copy knop staat of voeg nog 1 toe (iets in die richting)

**Comment by brtwrs** [comment]
Zit er nu in. Als dit is wat je bedoelt en zo goed is kan je het issue closen
