### ISSUE TITLE
UI: Status dropdown text not showing

### ISSUE THREAD

**Issue by brtwrs** [brtwrs/GCS-issues#5]
![Screenshot 2024-03-29 at 11 23 21](https://github.com/brtwrs/GCS-issues/assets/31477729/416ba8ea-2886-43d6-886b-55fe677e261b)

**Comment by AVorpen** [comment]
![Screenshot from 2024-03-31 00-39-21](https://github.com/brtwrs/GCS-issues/assets/68108917/278b77ab-05a9-4715-a0f7-5ba081b41366)
fixed!
