### ISSUE TITLE
port description

### ISSUE THREAD

**Issue by marcplaggenburg** [brtwrs/GCS-issues#8]
Nu is port description eigenlijk type poort. kan dit een kolom type connectie worden en dan
Type poort -> acces, trunk, p2p, ap, cam etc.

daarachter een veld description waar de crew: ap/p2p/sw nummers of eigen omschrijving kan toevoegen zodat engineer weet wat erop de poort aangesloten zit

**Comment by brtwrs** [comment]
Note

**Comment by marcplaggenburg** [comment]
tijdelijk via DB de velden:
- uplink
- trunk (doorlus)
- ap
- p2p
- cam
- access poort 
- ups
